# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: none

- script: |
    echo "Cloning GitHub repo..."
    git clone --depth 1 https://$(Tumm-by):$(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)@github.com/Tumm-by/GMI2J3_Projekt.git